"""
Proposition 3 -- the self-avoidance sweeps, in exact integer arithmetic.

Usage:
    python paths.py vonkoch  [N]   # von Koch curve to 4^N edges   (paper: N=9)
    python paths.py arrowhead [N]  # arrowhead curve to 3^N edges  (paper: N=13)
    python paths.py hilbert  [N]   # Hilbert curve to 4^N - 1 edges (paper: N=10)
    python paths.py all            # all three at the paper's orders

The von Koch and arrowhead curves live on the triangular lattice, so their
vertices are represented as Eisenstein integers a + b*omega with
omega = exp(i*pi/3): the six unit directions are omega^k, which in (a, b)
coordinates are (1,0), (0,1), (-1,1), (-1,0), (0,-1), (1,-1).  All arithmetic
is therefore exact integer arithmetic and no floating-point tolerance is
involved in deciding whether two vertices coincide.  The Hilbert curve lives on
the square lattice and is generated by the standard d2xy bit construction.
"""
import sys, time
import numpy as np

# the six unit Eisenstein directions, as (a, b) with point = a + b*omega
EIS = np.array([(1, 0), (0, 1), (-1, 1), (-1, 0), (0, -1), (1, -1)], dtype=np.int64)


def _lsystem(axiom, rules, n):
    s = axiom
    for _ in range(n):
        s = "".join(rules.get(c, c) for c in s)
    return s


def _walk_triangular(s, start_dir=0):
    """Walk an L-system string of F/+/- on the triangular lattice (60 deg turns)."""
    draw = np.fromiter((c == 'F' for c in s), dtype=bool, count=len(s))
    turn = np.fromiter(((1 if c == '+' else -1 if c == '-' else 0) for c in s),
                       dtype=np.int64, count=len(s))
    heading = (start_dir + np.cumsum(turn)) % 6          # heading AFTER each symbol
    h = np.concatenate([[start_dir % 6], heading[:-1]])   # heading when each symbol runs
    steps = EIS[h[draw]]
    pts = np.zeros((steps.shape[0] + 1, 2), dtype=np.int64)
    np.cumsum(steps, axis=0, out=pts[1:])
    return pts


def _distinct(pts):
    packed = (pts[:, 0] << 32) + pts[:, 1]     # exact: coordinates fit well inside int64
    return np.unique(packed).size


def _report(name, pts, expected_edges):
    v, e = pts.shape[0], pts.shape[0] - 1
    d = _distinct(pts)
    ok = (d == v)
    print(f"  {name:22s} edges {e:9d} (expected {expected_edges:9d})"
          f"  vertices {v:9d}  distinct {d:9d}  self-avoiding {'yes' if ok else 'NO'}")
    assert e == expected_edges, "edge count does not match the substitution rule"
    return ok


def vonkoch(n=9):
    print(f"=== von Koch curve, order {n} ===")
    s = _lsystem("F", {"F": "F+F--F+F"}, n)
    pts = _walk_triangular(s)
    return _report(f"von Koch n={n}", pts, 4 ** n)


def arrowhead(n=13):
    print(f"=== Sierpinski arrowhead curve, order {n} ===")
    # A -> B-A-B, B -> A+B+A, drawing on every letter
    s = _lsystem("A", {"A": "B-A-B", "B": "A+B+A"}, n)
    s = s.replace("A", "F").replace("B", "F")
    pts = _walk_triangular(s)
    return _report(f"arrowhead n={n}", pts, 3 ** n)


def hilbert(n=10):
    """Standard d2xy construction: the order-n curve visits all 4^n cells once."""
    print(f"=== Hilbert curve, order {n} ===")
    N = 1 << n
    t = np.arange(N * N, dtype=np.int64)
    x = np.zeros_like(t)
    y = np.zeros_like(t)
    tt = t.copy()
    s = 1
    while s < N:
        rx = 1 & (tt // 2)
        ry = 1 & (tt ^ rx)
        # rotate
        swap = (ry == 0)
        xr = np.where(swap & (rx == 1), s - 1 - x, x)
        yr = np.where(swap & (rx == 1), s - 1 - y, y)
        x2 = np.where(swap, yr, xr)
        y2 = np.where(swap, xr, yr)
        x, y = x2 + s * rx, y2 + s * ry
        tt //= 4
        s <<= 1
    pts = np.stack([x, y], axis=1)
    step = np.abs(np.diff(pts, axis=0)).sum(1)
    assert np.all(step == 1), "consecutive Hilbert vertices are not adjacent"
    return _report(f"Hilbert n={n}", pts, 4 ** n - 1)


if __name__ == "__main__":
    job = sys.argv[1] if len(sys.argv) > 1 else "all"
    arg = int(sys.argv[2]) if len(sys.argv) > 2 else None
    t0 = time.time()
    if job == "all":
        print("Proposition 3: control self-avoidance sweeps, exact integer arithmetic\n")
        vonkoch(9); arrowhead(13); hilbert(10)
    else:
        {"vonkoch": vonkoch, "arrowhead": arrowhead, "hilbert": hilbert}[job](
            arg or {"vonkoch": 9, "arrowhead": 13, "hilbert": 10}[job])
    print(f"\n[{time.time()-t0:.1f}s]")
